root: true

env:
  es6: true
  node: true

parserOptions:
  parser: '@babel/eslint-parser'
  ecmaVersion: 2021

extends:
  - eslint:recommended

rules:
  indent:
    - warn
    - 4
    - SwitchCase: 1
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
  no-unused-vars:
    - off
  comma-dangle:
    - warn
    - always-multiline
    