service: task-tracker

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${self:custom.region}
  environment:
    COLUMNS_TABLE_ARN: ${env:COLUMNS_TABLE_ARN}
    CARDS_TABLE_ARN: ${env:CARDS_TABLE_ARN}
    COLUMNS_TABLE_NAME: ${self:custom.columnsTableName}
    CARDS_TABLE_NAME: ${self:custom.cardsTableName}
    # DYNAMODB_ENDPOINT: http://localhost:8000

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:BatchWriteItem
          Resource: ${self:provider.environment.COLUMNS_TABLE_ARN}/*

plugins:
  - serverless-offline

custom:
  columnsTableName: adavydova-columns
  cardsTableName: adavydova-cards
  region: eu-west-1

functions:
  # ColumnController methods
  createColumn:
    handler: src/controller/ColumnController.createColumn
    timeout: 15
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /create-column
          method: POST
          cors: true

  getColumn:
    handler: src/controller/ColumnController.getColumn
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /get-column/{columnID}
          method: GET
          cors: true

  updateColumn:
    handler: src/controller/ColumnController.updateColumn
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /update-columns/{columnID}
          method: PUT
          cors: true

  deleteColumn:
    handler: src/controller/ColumnController.deleteColumn
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /delete-columns/{columnID}
          method: DELETE
          cors: true

  getColumns:
    handler: src/controller/ColumnController.getColumns
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /columns
          method: GET
          cors: true

  getMaxColumnIndex:
    handler: src/controller/ColumnController.getMaxColumnIndex
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /columns/maxIndex
          method: GET
          cors: true

  # CardController methods
  createCard:
    handler: src/controller/CardController.createCard
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /create-card/{columnID}
          method: POST
          cors: true

  getCard:
    handler: src/controller/CardController.getCard
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /get-card/{cardID}
          method: GET
          cors: true

  updateCard:
    handler: src/controller/CardController.updateCard
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /update-card/{cardID}
          method: PUT
          cors: true

  deleteCard:
    handler: src/controller/CardController.deleteCard
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /delete-card/{cardID}
          method: DELETE
          cors: true

  getCards:
    handler: src/controller/CardController.getCards
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /cards
          method: GET
          cors: true

  getCardsByColumnID:
    handler: src/controller/CardController.getCardsByColumnID
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /columns/{columnID}/cards
          method: GET
          cors: true

  moveCard:
    handler: src/controller/CardController.move
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /cards/{cardID}/{columnID}/{prevCardIndex}/{nextCardIndex}/move
          method: POST
          cors: true

  getMaxCardIndex:
    handler: src/controller/CardController.getMaxCardIndex
    # environment:
    #   DYNAMODB_ENDPOINT: http://localhost:8000
    events:
      - http:
          path: /columns/{columnID}/maxIndex
          method: GET
          cors: true

  
